version: '3.9'

services:
  mongo:
    image: mongo
    container_name: webflux_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    restart: always
    container_name: webflux_express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123
      ME_CONFIG_MONGODB_URL: mongodb://root:root123@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root123
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge


# https://stackoverflow.com/questions/42912755/how-to-create-a-db-for-mongodb-container-on-start-up
# mongo -u usuário-da-base -p senha-da-base host-de-conexao/nome-da-base
# mongosh "mongodb://andre:123456@localhost:27017/webflux?authSource=webflux"
# db.user.createIndex(
#  { email: 1 },
#  { unique: true, name: "indice_email_unico" }
#)

# db.user.createIndex(  { email: 1 },  { unique: true, name: "indice_email_unico" })
# db.user.getIndexes()