spring:
  application:
    name: webflux
  data:
    mongodb:
      uri: mongodb://andre:123456@localhost:27017/webflux?authSource=webflux
      #auto-index-creation: true
      #host: localhost
      #port: 27017
      #authentication-database: admin
      #username: ${DB_USER:root}
      #password: ${DB_PASSWORD:123456}
      #database: ${DB_NAME:webfluxdb}
#
